---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  labels:
    k8s-app: tbpolicy
  name: tbpolicy
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: tbpolicy
  template:
    metadata:
      labels:
        k8s-app: tbpolicy
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ''
    spec:
      containers:
      - name: tbpolicy
        image: hchenxa1986/tbpolicy:latest
        imagePullPolicy: IfNotPresent
      nodeSelector:
        beta.kubernetes.io/arch: 'x86_64'
        role: 'master'
      tolerations:
      - key: "dedicated"
        operator: "Equal"
        value: "master"
        effect: "NoSchedule"
      - key: "CriticalAddonsOnly"
        operator: "Exists"
